# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)
platform :android do
  desc "Build the app"
  lane :build_android do
    build_number = number_of_commits()
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "appbundle", "--build-number=#{build_number}")
    end
  end

  desc "Submit a new Beta Build to Google Play"
  lane :release_beta do
    upload_to_play_store(track: 'beta', version_code: 1, json_key_data: File.read('/tmp/upload-key.txt'))
  end

  desc "Submit a new Alpha Build to Google Play"
  lane :release_alpha do
    upload_to_play_store(track: 'internal', version_code: 1, json_key_data: File.read('/tmp/upload-key.txt'))
  end
end
